version: "3.9"
services:
  server:
    build: .
    depends_on:
      - postgres
    restart: always
    env_file: .env.docker
    ports:
      - "9999:9999"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backup
