use_small_heuristics = "Max"
struct_lit_width = 50
chain_width = 70
max_width = 110

# currently requires nightly
overflow_delimited_expr = true

imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
imports_indent = "Block"
