use_small_heuristics = "Max"
struct_lit_width = 30
chain_width = 65

# currently requires nightly
overflow_delimited_expr = true

imports_granularity = "Crate"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
imports_indent = "Block"
